# 近似値を求める練習

In [302]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('20060825.png')


w = np.genfromtxt('w.csv', delimiter=',')
w = w[1:,4:]
area = w.astype(np.int64)
tmp = img[area[:,0],area[:,1]]
uv = [[255, 255, 255],
          [255, 217, 217],
          [255, 203, 153],
          [190, 255, 255],
          [150, 250, 250],
          [0,    246, 250],
          [0,    200, 255],
          [0,    140, 255],
          [0,    90,   250],
          [0,    20,   255],
          [33,   0,    165],
          [91,   0,    181],
          [106, 0,    204],
          [204, 0,    204]]

print(area[33])
print(tmp[33])
print(uv[1])
print(np.allclose(tmp, uv[1], rtol=1e-01, atol=1e-08))


[151 240]
[  0 140 255]
[255, 217, 217]
False


# 各エリアがどこに属するか抽出

In [303]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('20060825.png')


w = np.genfromtxt('w.csv', delimiter=',')
w = w[1:,4:]
area = w.astype(np.int64)
tmp = img[area[:,0],area[:,1]]
uv = [[255, 255, 255],
          [255, 217, 217],
          [255, 203, 153],
          [190, 255, 255],
          [150, 250, 250],
          [0,    246, 250],
          [0,    200, 255],
          [0,    140, 255],
          [0,    90,   250],
          [0,    20,   255],
          [33,   0,    165],
          [91,   0,    181],
          [106, 0,    204],
          [204, 0,    204]]

#csv = (tmp == uv0).all(axis=1)
for i in range(14):
    #print(uv[i])
    tako = []
    for j in range(142):
        if np.allclose(tmp[j], uv[i], rtol=1e-01, atol=1e-08) == True:
            tako.append(j)
    print(tako)

[]
[]
[]
[]
[46]
[0, 2, 6, 39, 42, 47, 48, 49, 57, 108]
[1, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 22, 24, 29, 34, 40, 43, 50, 58, 89, 92, 106]
[20, 21, 23, 27, 28, 30, 31, 32, 33, 35, 36, 37, 38, 45, 54, 56, 59, 60, 66, 67, 68, 69, 70, 71, 73, 74, 75, 76, 78, 79, 80, 82, 88, 90, 91, 93, 94, 95]
[44, 51, 53, 61, 63, 65, 77, 81, 83, 84, 85, 86, 87, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 109, 110, 111, 112, 113, 114, 115, 116, 117, 120, 121, 122, 123, 124, 125, 127, 128, 129, 130, 132, 133, 134]
[131, 135, 136, 137, 140, 141]
[138, 139]
[]
[]
[]


# ミスマッチ(近似値)の抽出

In [368]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('2006/20061231.png')


w = np.genfromtxt('w.csv', delimiter=',')
w = w[1:,4:]
area = w.astype(np.int64)
tmp = img[area[:,0],area[:,1]]
uv = [[255, 255, 255],
          [255, 217, 217],
          [255, 203, 153],
          [190, 255, 255],
          [150, 250, 250],
          [0,    246, 250],
          [0,    200, 255],
          [0,    140, 255],
          [0,    90,   250],
          [0,    20,   255],
          [33,   0,    165],
          [91,   0,    181],
          [106, 0,    204],
          [204, 0,    204]]

csv = npdata = np.zeros(142)
for j in range(142):
    tako = []
    for i in range(14):
        tako.append(np.linalg.norm(tmp[j]-uv[i]))
        csv[j] = i
    csv[j] = tako.index(min(tako))
        
        
print(csv)


[ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  2.  2.  2.
  1.  2.  2.  2.  2.  2.  2.  1.  3.  4.  2.  2.  2.  2.  2.  2.  2.  2.
  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  1.  1.  1.  1.  2.  2.
  2.  1.  2.  2.  2.  2.  1.  2.  2.  2.  1.  2.  2.  2.  2.  2.  2.  2.
  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  3.  2.  2.  2.
  2.  2.  2.  2.  2.  2.  2.  2.  2.  3.  2.  2.  2.  2.  2.  3.  3.  3.
  3.  3.  3.  3.  2.  2.  3.  3.  3.  2.  2.  3.  2.  4.  2.  2.]


# ミスマッチ(Where)の抽出

In [308]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('20060101.png')


w = np.genfromtxt('w.csv', delimiter=',')
w = w[1:,4:]
area = w.astype(np.int64)
tmp = img[area[:,0],area[:,1]]
uv0 =   [255, 255, 255]
uv1 =   [255, 217, 217]
uv2 =   [255, 203, 153]
uv3 =   [190, 255, 255]
uv4 =   [150, 250, 250]
uv5 =   [0,    246, 250]
uv6 =   [0,    200, 255]
uv7 =   [0,    140, 255]
uv8 =   [0,    90,   250]
uv9 =   [0,    20,   255]
uv10 = [33,   0,    165]
uv11 = [91,   0,    181]
uv12 = [106, 0,    204]
uv13 = [204, 0,    204]

csv = (tmp == uv0).all(axis=1)
print(area[33])
print(tmp[33])
print(uv1)
print(np.allclose(tmp[33], uv1, rtol=1e-05, atol=1e-08))
csv[np.where((tmp == uv1).all(axis=1))] = True
csv[np.where((tmp == uv2).all(axis=1))] = True
csv[np.where((tmp == uv3).all(axis=1))] = True
csv[np.where((tmp == uv4).all(axis=1))] = True
csv[np.where((tmp == uv5).all(axis=1))] = True
csv[np.where((tmp == uv6).all(axis=1))] = True
csv[np.where((tmp == uv7).all(axis=1))] = True
csv[np.where((tmp == uv8).all(axis=1))] = True
csv[np.where((tmp == uv9).all(axis=1))] = True
csv[np.where((tmp == uv10).all(axis=1))] = True
csv[np.where((tmp == uv11).all(axis=1))] = True
csv[np.where((tmp == uv12).all(axis=1))] = True
csv[np.where((tmp == uv13).all(axis=1))] = True


print("======== Failed: mismatch ============")
print(np.where(csv == False))
print(area[22])
print(tmp[22])


[151 240]
[255 214 200]
[255, 217, 217]
False
======== Failed: mismatch ============
(array([ 33, 118]),)
[102 257]
[255 217 217]


# エリアごとのマッピング

In [297]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('20060101.png')


w = np.genfromtxt('w.csv', delimiter=',')
w = w[1:,4:]
area = w.astype(np.int64)
tmp = img[area[:,0],area[:,1]]
uv0 =   [255, 255, 255]
uv1 =   [255, 217, 217]
uv2 =   [255, 203, 153]
uv3 =   [190, 255, 255]
uv4 =   [150, 250, 250]
uv5 =   [0,    246, 250]
uv6 =   [0,    200, 255]
uv7 =   [0,    140, 255]
uv8 =   [0,    90,   250]
uv9 =   [0,    20,   255]
uv10 = [33,   0,    165]
uv11 = [91,   0,    181]
uv12 = [106, 0,    204]
uv13 = [204, 0,    204]

csv = (tmp == uv0).all(axis=1)
print(np.allclose(tmp[33], uv2, rtol=1e-05, atol=1e-08))
csv[np.where((tmp == uv1).all(axis=1))] = True
csv[np.where((tmp == uv2).all(axis=1))] = True
csv[np.where((tmp == uv3).all(axis=1))] = True
csv[np.where((tmp == uv4).all(axis=1))] = True
csv[np.where((tmp == uv5).all(axis=1))] = True
csv[np.where((tmp == uv6).all(axis=1))] = True
csv[np.where((tmp == uv7).all(axis=1))] = True
csv[np.where((tmp == uv8).all(axis=1))] = True
csv[np.where((tmp == uv9).all(axis=1))] = True
csv[np.where((tmp == uv10).all(axis=1))] = True
csv[np.where((tmp == uv11).all(axis=1))] = True
csv[np.where((tmp == uv12).all(axis=1))] = True
csv[np.where((tmp == uv13).all(axis=1))] = True

print("")
print("======== Success: match ============")
print(np.where((tmp == uv0).all(axis=1)))
print(np.where((tmp == uv1).all(axis=1)))
print(np.where((tmp == uv2).all(axis=1)))
print(np.where((tmp == uv3).all(axis=1)))
print(np.where((tmp == uv4).all(axis=1)))
print(np.where((tmp == uv5).all(axis=1)))
print(np.where((tmp == uv6).all(axis=1)))
print(np.where((tmp == uv7).all(axis=1)))
print(np.where((tmp == uv8).all(axis=1)))
print(np.where((tmp == uv9).all(axis=1)))
print(np.where((tmp == uv10).all(axis=1)))
print(np.where((tmp == uv11).all(axis=1)))
print(np.where((tmp == uv12).all(axis=1)))
print(np.where((tmp == uv13).all(axis=1)))
#print(tmp[np.where(tmp == y)[0]])



False

======== Success: match ============
(array([], dtype=int64),)
(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  28,  29,  34,  39,  42,  43,  44,  46,  47,  48,  49,  57,
       103, 120, 127, 129]),)
(array([ 27,  30,  31,  32,  35,  36,  37,  38,  40,  41,  50,  51,  52,
        53,  54,  55,  56,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 104, 105, 106,
       107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 119, 121,
       122, 123, 124, 125, 126, 128, 130, 131, 132, 133, 134, 137, 140]),)
(array([ 45, 135, 136, 138, 139, 141]),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(arr

# HSV

In [305]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('20060825.png')
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV_FULL)
h = hsv[:, :, 0]
s = hsv[:, :, 1]
mask = np.zeros(h.shape, dtype=np.uint8)
mask[((h < 20) | (h > 200)) & (s > 128)] = 255
print(mask.shape)

(352, 420)


# 年度別紫外線データ数値化

In [360]:
import cv2
import numpy as np
import os

w = np.genfromtxt('w.csv', delimiter=',')
w = w[1:,4:]
area = w.astype(np.int64)


data = []
for year in range(2006, 2006):
    files = os.listdir(str(year))
    for file in files:
        img = cv2.imread(str(year) + "/"+ file)
        tmp = img[area[:,0],area[:,1]]

        uv = [[255, 255, 255],
                  [255, 217, 217],
                  [255, 203, 153],
                  [190, 255, 255],
                  [150, 250, 250],
                  [0,    246, 250],
                  [0,    200, 255],
                  [0,    140, 255],
                  [0,    90,   250],
                  [0,    20,   255],
                  [33,   0,    165],
                  [91,   0,    181],
                  [106, 0,    204],
                  [204, 0,    204]]

        csv = npdata = np.zeros(142)
        for j in range(142):
            tako = []
            for i in range(14):
                tako.append(np.linalg.norm(tmp[j]-uv[i]))
                csv[j] = i
            csv[j] = tako.index(min(tako))

        data.append(csv)a

# print(data)

# DataFrameの作成

In [2]:
import cv2
import pandas as pd
import os


pd.read_csv("w.csv")


No.       都市名      Y(緯度）       X(経度)  Yのピクセル  Xのピクセル
0      1    北海道 稚内  45.415664  141.673082      17     255
1      2    北海道 旭川  43.770635  142.364819      41     263
2      3    北海道 留萌  43.940987  141.637012      38     255
3      4    北海道 札幌  43.062096  141.354376      51     251
4      5   北海道 岩見沢  43.196205  141.775933      49     256
5      6   北海道 倶知安  42.901829  140.758698      53     243
6      7    北海道 網走  44.020632  144.273398      38     287
7      8    北海道 北見  43.804031  143.895876      40     282
8      9    北海道 紋別  44.356484  143.354503      34     276
9     10    北海道 根室  43.330076  145.582790      47     303
10    11    北海道 釧路  42.984854  144.381356      52     288
11    12    北海道 帯広  42.923899  143.196103      53     274
12    13    北海道 室蘭  42.315231  140.973799      62     246
13    14    北海道 浦河  42.168516  142.768120      64     268
14    15    北海道 函館  41.768793  140.728810      70     243
15    16    北海道 江差  41.869156  140.127460      69     236
16    17    青森県 青森  40.824308  140.739998      84     243
17    18    青森県 むつ  41.292746  141.183475      77     249
18    19    青森県 八戸  40.512284  141.488399      88     252
19    20    秋田県 秋田  39.718614  140.102364     100     235
20    21    秋田県 横手  39.313782  140.566649     106     241
21    22    岩手県 盛岡  39.702053  141.154484     101     248
22    23    岩手県 宮古  39.641420  141.957140     102     257
23    24   岩手県 大船渡  39.081901  141.708530     110     255
24    25    宮城県 仙台  38.268215  140.869356     122     245
25    26    宮城県 白石  38.002478  140.619860     126     242
26    27    山形県 山形  38.240435  140.363633     123     238
27    28    山形県 米沢  37.922240  140.116781     127     235
28    29    山形県 酒田  38.914786  139.836571     113     233
29    30    山形県 新庄  38.765015  140.301608     115     238
..   ...       ...        ...         ...     ...     ...
112  113   福岡県 久留米  33.319286  130.508374     198     115
113  114    大分県 大分  33.238172  131.612619     204     128
114  115    大分県 中津  33.598221  131.188325     201     123
115  116    大分県 日田  33.321333  130.940966     198     120
116  117    大分県 佐伯  32.959806  131.900058     204     132
117  118    長崎県 長崎  32.750286  129.877667     213     107
118  119   長崎県 佐世保  33.179915  129.715110     205     106
119  120    長崎県 厳原  34.202646  129.287521     188     100
120  121    長崎県 福江  32.701861  128.757760     207      93
121  122    佐賀県 佐賀  33.249442  130.299794     200     112
122  123   佐賀県 伊万里  33.264586  129.880269     199     107
123  124    熊本県 熊本  32.789827  130.741667     206     118
124  125  熊本県 阿蘇乙姫  32.943445  131.043434     204     122
125  126    熊本県 牛深  32.190683  130.026223     222     111
126  127    熊本県 人吉  32.210041  130.762554     216     118
127  128    宮崎県 宮崎  31.911096  131.423893     223     124
128  129    宮崎県 延岡  32.582272  131.665009     210     129
129  130    宮崎県 都城  31.719590  131.061621     223     122
130  131   宮崎県 高千穂  32.711690  131.307787     209     125
131  132   鹿児島県 名瀬  28.367285  129.500979     278      99
132  133  鹿児島県 鹿児島  31.596553  130.557116     229     113
133  134   鹿児島県 鹿屋  31.378292  130.852077     229     119
134  135  鹿児島県 種子島  30.609558  130.978877     248     117
135  136    沖縄県 那覇  26.212312  127.679157     312      76
136  137    沖縄県 名護  26.591547  127.977316     303      83
137  138   沖縄県 久米島  26.350396  126.771177     309      66
138  139  沖縄県 南大東島  25.828898  131.231876     318     124
139  140   沖縄県 宮古島  24.805490  125.281149     331      48
140  141   沖縄県 石垣島  24.406403  124.175444     342      34
141  142  沖縄県 与那国町  24.467969  123.004453     342      19

[142 rows x 6 columns]